#base os 
FROM almalinux:9
#we can override the cmd instruction
CMD ["google.com"]
#we can't override entrypoint instruction, if we try to override entrypoint it won't override but it will append
ENTRYPOINT ["ping"]