# FROM almalinux:9
# ENV course="Devops with AWS" \
#     duration="120hrs" \
#     trainer="Siva"
# RUN echo "hello ${trainer}" > /tmp/Devops.txt
# CMD ["sleep", "100"]


FROM almalinux:9
ENV course="Devops with AWS" \
    duration="120hrs" \
    trainer="Siva"
ARG USERNAME=Lakshman
RUN echo "hello user: ${USERNAME}""
CMD ["sleep", "100"]