FROM almalinux:9
ENV course="Devops with AWS" \
    duration="120hrs" \
    trainer="Siva"
RUN echo "hello ${trainer}" > Devops.txt
CMD ["sleep", "100"]


# from amlalinux:9
# run mkdir /tmp/work-dir-demo
# workdir /tmp/work-dir-demo
# run pwd
# run echo "hello from work dir" > hello.txt